trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Dev
  displayName: 'Deploy to DEV'
  variables:
    - group: vg-fabric-dev
  jobs:
  - job: DeployDev
    steps:
    - checkout: self
    - task: AzureCLI@2
      displayName: 'Deploy DEV Infra'
      inputs:
        azureSubscription: 'sc-azure-fabric'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az deployment sub create             --name deploy-fabric-dev             --location "UK South"             --template-file infra/main.bicep             --parameters @infra/parameters-dev.json

- stage: Test
  displayName: 'Deploy to TEST'
  dependsOn: Dev
  variables:
    - group: vg-fabric-test
  jobs:
  - job: DeployTest
    steps:
    - checkout: self
    - task: AzureCLI@2
      displayName: 'Deploy TEST Infra'
      inputs:
        azureSubscription: 'sc-azure-fabric'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az deployment sub create             --name deploy-fabric-test             --location "UK South"             --template-file infra/main.bicep             --parameters @infra/parameters-test.json

- stage: UAT
  displayName: 'Deploy to UAT'
  dependsOn: Test
  variables:
    - group: vg-fabric-uat
  jobs:
  - job: DeployUAT
    steps:
    - checkout: self
    - task: AzureCLI@2
      displayName: 'Deploy UAT Infra'
      inputs:
        azureSubscription: 'sc-azure-fabric'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az deployment sub create             --name deploy-fabric-uat             --location "UK South"             --template-file infra/main.bicep             --parameters @infra/parameters-uat.json

- stage: Prod
  displayName: 'Deploy to PROD'
  dependsOn: UAT
  variables:
    - group: vg-fabric-prod
  jobs:
  - job: DeployProd
    steps:
    - checkout: self
    - task: AzureCLI@2
      displayName: 'Deploy PROD Infra'
      inputs:
        azureSubscription: 'sc-azure-fabric'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az deployment sub create             --name deploy-fabric-prod             --location "UK South"             --template-file infra/main.bicep             --parameters @infra/parameters-prod.json




      - stage: Dev
  displayName: 'Deploy to DEV'
  variables:
    - group: vg-fabric-dev

  jobs:
  - job: DeployDev
    displayName: 'Deploy DEV Infra'
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: 'Deploy DEV Infra'
      inputs:
        azureSubscription: 'sc-azure-fabric'
        scriptType: bash
        scriptLocation: inlineScript
        failOnStandardError: true        # treat stderr as failure as well
        inlineScript: |
          set -euo pipefail              # stop on first error

          DEPLOY_NAME="deploy-fabric-dev-$(date +%s)"
          TEMPLATE_FILE="infra/main.bicep"
          PARAM_FILE="infra/Parameter-azure-fabric.json"
          LOCATION="uksouth"

          echo "=== DEV: starting subscription deployment ==="
          echo "Deployment name : $DEPLOY_NAME"
          echo "Template        : $TEMPLATE_FILE"
          echo "Parameters file : $PARAM_FILE"
          echo "Location        : $LOCATION"
          echo

          # Run the deployment
          az deployment sub create \
            --name "$DEPLOY_NAME" \
            --location "$LOCATION" \
            --template-file "$TEMPLATE_FILE" \
            --parameters @"$PARAM_FILE" \
            --only-show-errors

          echo
          echo "=== DEV: checking deployment provisioningState ==="
          STATE=$(az deployment sub show \
            --name "$DEPLOY_NAME" \
            --query "properties.provisioningState" \
            -o tsv)

          echo "Deployment state: $STATE"

          if [ "$STATE" != "Succeeded" ]; then
            echo "Deployment did NOT succeed (state=$STATE). Showing failed operations..."
            az deployment operation sub list \
              --name "$DEPLOY_NAME" \
              --query "[?properties.provisioningState=='Failed'].
                        {type:properties.targetResource.resourceType,
                         name:properties.targetResource.resourceName,
                         status:properties.statusMessage}" \
              -o jsonc || true
            exit 1
          fi

          echo
          echo "=== DEV: deployment succeeded ==="

          echo
          echo "=== DEV: all operations (summary) ==="
          az deployment operation sub list \
            --name "$DEPLOY_NAME" \
            --query "[].{type:properties.targetResource.resourceType,
                         name:properties.targetResource.resourceName,
                         state:properties.provisioningState}" \
            -o table




- stage: Test
  displayName: 'Deploy to TEST'
  variables:
    - group: vg-fabric-test

  jobs:
  - job: DeployTest
    displayName: 'Deploy TEST Infra'
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: 'Deploy TEST Infra'
      inputs:
        azureSubscription: 'sc-azure-fabric'
        scriptType: bash
        scriptLocation: inlineScript
        failOnStandardError: true
        inlineScript: |
          set -euo pipefail

          cd "$(System.DefaultWorkingDirectory)"

          DEPLOY_NAME="deploy-fabric-test"   # fixed, known name
          TEMPLATE_FILE="infra/main.bicep"
          PARAM_FILE="infra/Parameter-azure-fabric-test.json"
          LOCATION="uksouth"

          echo "=== TEST: starting subscription deployment ==="
          echo "Deployment name : $DEPLOY_NAME"
          echo "Template        : $TEMPLATE_FILE"
          echo "Parameters file : $PARAM_FILE"
          echo "Location        : $LOCATION"
          echo

          # Run the deployment and capture the provisioning state directly
          STATE=$(az deployment sub create \
            --name "$DEPLOY_NAME" \
            --location "$LOCATION" \
            --template-file "$TEMPLATE_FILE" \
            --parameters @"$PARAM_FILE" \
            --query "properties.provisioningState" \
            -o tsv)

          echo "Deployment provisioningState: $STATE"

          if [ "$STATE" != "Succeeded" ]; then
            echo
            echo "=== TEST: Deployment FAILED (state=$STATE). 
Showing failed operations if any... ==="

            # Best effort: list failed operations, but don't break if the deployment isn't recorded
            az deployment operation sub list \
              --name "$DEPLOY_NAME" \
              --query "[?properties.provisioningState=='Failed'].
                        {type:properties.targetResource.resourceType,
                         name:properties.targetResource.resourceName,
                         status:properties.statusMessage}" \
              -o jsonc || echo "No operations found or deployment not recorded."

            exit 1
          fi

          echo
          echo "=== TEST: deployment SUCCEEDED. Summary of operations: ==="
          az deployment operation sub list \
            --name "$DEPLOY_NAME" \
            --query "[].{type:properties.targetResource.resourceType,
                         name:properties.targetResource.resourceName,
                         state:properties.provisioningState}" \
            -o table || echo "Could not list operations (but deployment succeeded)."
