# Triggers only when main changes, and only if relevant paths changed
trigger:
  branches: { include: [ main ] }
  paths:
    include:
      - factory/*
      - azure-piplines/parameters/*
      - arm-template-parameters-definition.json

pr: none

variables:
  serviceConnection: 'AZURE_SVC_CONN' # Azure RM service connection name
  # ADF resource ID used for validate/export (point at DEV factory)
  factoryResourceId: '/subscriptions/<SUB-ID-DEV>/resourceGroups/<RG-DEV>/providers/Microsoft.DataFactory/factories/<ADF-DEV-NAME>'

stages:
# ===== Build: validate + export (auto-publish) =====
- stage: Build_ARM
  displayName: Build (validate + export from /factory)
  jobs:
  - job: BuildExport
    pool: { vmImage: 'ubuntu-latest' }
    steps:
    - checkout: self
      clean: true

    - task: UseNode@1
      displayName: Use Node.js 20
      inputs: { version: '20.x' }

    - task: Npm@1
      displayName: Install ADF utilities
      inputs:
        command: 'ci'
        workingDir: '$(Build.SourcesDirectory)'

    # Validate authored JSON in /factory against your DEV ADF (schemas)
    - task: Npm@1
      displayName: Validate ADF
      inputs:
        command: 'custom'
        workingDir: '$(Build.SourcesDirectory)'
        customCommand: >
          run adf validate $(Build.SourcesDirectory)/factory $(factoryResourceId)

    # Export == publish → produces ARMTemplateForFactory.json (+ params)
    - task: Npm@1
      displayName: Export ARM (auto-publish)
      inputs:
        command: 'custom'
        workingDir: '$(Build.SourcesDirectory)'
        customCommand: >
          run adf export $(Build.SourcesDirectory)/factory $(factoryResourceId) ArmTemplate

    - task: PublishPipelineArtifact@1
      displayName: Publish ARM artifact
      inputs:
        targetPath: '$(Build.SourcesDirectory)/ArmTemplate'
        artifact: 'ArmTemplates'
        publishLocation: 'pipeline'

# ===== DEV =====
- stage: Dev
  displayName: Deploy to DEV
  dependsOn: Build_ARM
  variables:
    subscriptionId: '<SUBSCRIPTION-ID-DEV>'
    resourceGroup:  '<RG-DEV>'
    location:       'westeurope'
    paramFile:      'azure-piplines/parameters/adf.dev.parameters.json'
  jobs:
  - job: DeployDev
    pool: { vmImage: 'windows-latest' }
    steps:
    - checkout: self
    - download: current
      artifact: ArmTemplates

    - task: AzurePowerShell@5
      displayName: Stop ADF triggers (DEV)
      inputs:
        azureSubscription: $(serviceConnection)
        ScriptType: InlineScript
        Inline: |
          Import-Module Az.DataFactory -Force
          $df = Get-AzDataFactoryV2 -ResourceGroupName "$(resourceGroup)"
          $ts = Get-AzDataFactoryV2Trigger -ResourceGroupName "$(resourceGroup)" -DataFactoryName $df.Name -ErrorAction SilentlyContinue
          if ($ts) { $ts | Where-Object RuntimeState -eq 'Started' | ForEach-Object {
            Stop-AzDataFactoryV2Trigger -ResourceGroupName "$(resourceGroup)" -DataFactoryName $df.Name -Name $_.Name -Force } }
        azurePowerShellVersion: LatestVersion

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: ARM deploy (DEV)
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroup)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/ArmTemplates/ARMTemplateForFactory.json'
        # Use your curated per-env parameters:
        csmParametersFile: '$(Build.SourcesDirectory)/$(paramFile)'
        deploymentMode: 'Incremental'

    - task: AzurePowerShell@5
      displayName: Start ADF triggers (DEV)
      inputs:
        azureSubscription: $(serviceConnection)
        ScriptType: InlineScript
        Inline: |
          Import-Module Az.DataFactory -Force
          $df = Get-AzDataFactoryV2 -ResourceGroupName "$(resourceGroup)"
          $ts = Get-AzDataFactoryV2Trigger -ResourceGroupName "$(resourceGroup)" -DataFactoryName $df.Name -ErrorAction SilentlyContinue
          if ($ts) { $ts | Where-Object RuntimeState -ne 'Started' | ForEach-Object {
            Start-AzDataFactoryV2Trigger -ResourceGroupName "$(resourceGroup)" -DataFactoryName $df.Name -Name $_.Name -Force } }
        azurePowerShellVersion: LatestVersion

# ===== TEST =====
- stage: Test
  displayName: Deploy to TEST
  dependsOn: Dev
  condition: succeeded()
  variables:
    subscriptionId: '<SUBSCRIPTION-ID-TEST>'
    resourceGroup:  '<RG-TEST>'
    location:       'westeurope'
    paramFile:      'azure-piplines/parameters/adf.test.parameters.json'
  jobs:
  - job: DeployTest
    pool: { vmImage: 'windows-latest' }
    steps:
    - checkout: self
    - download: current
      artifact: ArmTemplates

    - task: AzurePowerShell@5
      displayName: Stop ADF triggers (TEST)
      inputs:
        azureSubscription: $(serviceConnection)
        ScriptType: InlineScript
        Inline: |
          Import-Module Az.DataFactory -Force
          $df = Get-AzDataFactoryV2 -ResourceGroupName "$(resourceGroup)"
          Get-AzDataFactoryV2Trigger -ResourceGroupName "$(resourceGroup)" -DataFactoryName $df.Name -ErrorAction SilentlyContinue |
            Where-Object RuntimeState -eq 'Started' |
            ForEach-Object { Stop-AzDataFactoryV2Trigger -ResourceGroupName "$(resourceGroup)" -DataFactoryName $df.Name -Name $_.Name -Force }
        azurePowerShellVersion: LatestVersion

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: ARM deploy (TEST)
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroup)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/ArmTemplates/ARMTemplateForFactory.json'
        csmParametersFile: '$(Build.SourcesDirectory)/$(paramFile)'
        deploymentMode: 'Incremental'

    - task: AzurePowerShell@5
      displayName: Start ADF triggers (TEST)
      inputs:
        azureSubscription: $(serviceConnection)
        ScriptType: InlineScript
        Inline: |
          Import-Module Az.DataFactory -Force
          $df = Get-AzDataFactoryV2 -ResourceGroupName "$(resourceGroup)"
          Get-AzDataFactoryV2Trigger -ResourceGroupName "$(resourceGroup)" -DataFactoryName $df.Name -ErrorAction SilentlyContinue |
            Where-Object RuntimeState -ne 'Started' |
            ForEach-Object { Start-AzDataFactoryV2Trigger -ResourceGroupName "$(resourceGroup)" -DataFactoryName $df.Name -Name $_.Name -Force }
        azurePowerShellVersion: LatestVersion

# ===== PROD =====
- stage: Prod
  displayName: Deploy to PROD
  dependsOn: Test
  condition: succeeded()
  variables:
    subscriptionId: '<SUBSCRIPTION-ID-PROD>'
    resourceGroup:  '<RG-PROD>'
    location:       'westeurope'
    paramFile:      'azure-piplines/parameters/adf.prod.parameters.json'
  jobs:
  - job: DeployProd
    pool: { vmImage: 'windows-latest' }
    steps:
    - checkout: self
    - download: current
      artifact: ArmTemplates

    - task: AzurePowerShell@5
      displayName: Stop ADF triggers (PROD)
      inputs:
        azureSubscription: $(serviceConnection)
        ScriptType: InlineScript
        Inline: |
          Import-Module Az.DataFactory -Force
          $df = Get-AzDataFactoryV2 -ResourceGroupName "$(resourceGroup)"
          Get-AzDataFactoryV2Trigger -ResourceGroupName "$(resourceGroup)" -DataFactoryName $df.Name -ErrorAction SilentlyContinue |
            Where-Object RuntimeState -eq 'Started' |
            ForEach-Object { Stop-AzDataFactoryV2Trigger -ResourceGroupName "$(resourceGroup)" -DataFactoryName $df.Name -Name $_.Name -Force }
        azurePowerShellVersion: LatestVersion

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: ARM deploy (PROD)
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroup)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/ArmTemplates/ARMTemplateForFactory.json'
        csmParametersFile: '$(Build.SourcesDirectory)/$(paramFile)'
        deploymentMode: 'Incremental'

    - task: AzurePowerShell@5
      displayName: Start ADF triggers (PROD)
      inputs:
        azureSubscription: $(serviceConnection)
        ScriptType: InlineScript
        Inline: |
          Import-Module Az.DataFactory -Force
          $df = Get-AzDataFactoryV2 -ResourceGroupName "$(resourceGroup)"
          Get-AzDataFactoryV2Trigger -ResourceGroupName "$(resourceGroup)" -DataFactoryName $df.Name -ErrorAction SilentlyContinue |
            Where-Object RuntimeState -ne 'Started' |
            ForEach-Object { Start-AzDataFactoryV2Trigger -ResourceGroupName "$(resourceGroup)" -DataFactoryName $df.Name -Name $_.Name -Force }
        azurePowerShellVersion: LatestVersion





        # 0) Download the build artifact to a deterministic path
- task: DownloadPipelineArtifact@2
  displayName: Download ArmTemplates artifact
  inputs:
    artifact: ArmTemplates
    path: $(System.ArtifactsDirectory)

# 1) Show what we got (helps diagnose paths/casing)
- powershell: |
    "ArtifactsDir: $(System.ArtifactsDirectory)"
    Get-ChildItem -Recurse "$(System.ArtifactsDirectory)\ArmTemplates" | Select FullName
  displayName: List ARM files

# 2) Auto-discover the actual root template & parameters (handles casing)
- powershell: |
    $root = "$(System.ArtifactsDirectory)\ArmTemplates"
    $arm = Get-ChildItem -Recurse $root -Filter *ARMTemplate*Factory*.json | Select-Object -First 1
    if (-not $arm) { throw "ARM template not found under $root" }
    $par = Get-ChildItem -Recurse $root -Filter *ARMTemplateParameters*Factory*.json | Select-Object -First 1
    if (-not $par) { throw "Parameters file not found under $root" }
    "Template: $($arm.FullName)"
    "Params:   $($par.FullName)"
    Write-Host "##vso[task.setvariable variable=armTemplate]$($arm.FullName)"
    Write-Host "##vso[task.setvariable variable=armParams]$($par.FullName)"
    Write-Host "##vso[task.setvariable variable=armDir]$($arm.DirectoryName)"
  displayName: Find ARM files

# 3) (Optional) normalize to UTF-8 (no BOM) — safe on Win/Linux agents
- powershell: |
    $files = @("$(armTemplate)", "$(armParams)")
    foreach ($f in $files) {
      $txt = Get-Content -Raw $f
      $enc = New-Object System.Text.UTF8Encoding($false)
      [System.IO.File]::WriteAllText($f, $txt, $enc)
    }
  displayName: Normalize encoding

# 4) Deploy using Azure CLI (resolves linkedTemplates relative to the root)
- task: AzureCLI@2
  displayName: Deploy ADF (DEV) via az
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: pscore
    scriptLocation: inlineScript
    workingDirectory: '$(armDir)'
    inlineScript: |
      az deployment group create `
        --resource-group "$(resourceGroup)" `
        --mode Incremental `
        --template-file "$(armTemplate)" `
        --parameters @"$(armParams)"

