trigger: none

variables:
  armPath: 'adf/ARMTemplate'
  paramPath: 'adf/ARMTemplate/parameters'
  location: 'East US'
  azureSubscription: 'Azure-Service-Connection'

stages:

- template: templates/adf-deploy-stage.yml
  parameters:
    stageName: Dev
    azureSubscription: $(azureSubscription)
    resourceGroupName: rg-adf-dev
    dataFactoryName: adf-dev
    location: $(location)
    armTemplatePath: $(armPath)
    parameterFilePath: '$(paramPath)/dev.parameters.json'

- template: templates/adf-deploy-stage.yml
  parameters:
    stageName: Test
    azureSubscription: $(azureSubscription)
    resourceGroupName: rg-adf-test
    dataFactoryName: adf-test
    location: $(location)
    armTemplatePath: $(armPath)
    parameterFilePath: '$(paramPath)/test.parameters.json'

- template: templates/adf-deploy-stage.yml
  parameters:
    stageName: UAT
    azureSubscription: $(azureSubscription)
    resourceGroupName: rg-adf-uat
    dataFactoryName: adf-uat
    location: $(location)
    armTemplatePath: $(armPath)
    parameterFilePath: '$(paramPath)/uat.parameters.json'

- template: templates/adf-deploy-stage.yml
  parameters:
    stageName: Prod
    azureSubscription: $(azureSubscription)
    resourceGroupName: rg-adf-prod
    dataFactoryName: adf-prod
    location: $(location)
    armTemplatePath: $(armPath)
    parameterFilePath: '$(paramPath)/prod.parameters.json'
