trigger: none   # manual run

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'SC-NAME'      # your service connection
  location: 'uksouth'

stages:
- stage: Deploy
  displayName: 'Deploy RG + Storage (Subscription Scope)'
  jobs:
  - job: Run
    displayName: 'Run Bicep deployment'
    steps:
    - checkout: self

    # Print info
    - task: AzureCLI@2
      displayName: 'Print environment details'
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "===================================================="
          echo "Azure Subscription Connection: $(azureServiceConnection)"
          echo "Location: $(location)"
          echo "Build Directory: $(Build.SourcesDirectory)"
          echo "===================================================="
          az account show --output table

    # Compile (optional check)
    - task: AzureCLI@2
      displayName: 'Validate Bicep syntax'
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az bicep version || az bicep install
          az bicep build --file infra/main.bicep --outfile out/main.json
          echo "✅ Bicep compiled successfully -> out/main.json"

    # What-if (Preview)
    - task: AzureCLI@2
      displayName: 'What-if Deployment'
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "🔎 Running WHAT-IF (Subscription Scope)..."
          az deployment sub what-if \
            --name "whatif-storage-$(Build.BuildId)" \
            --location "$(location)" \
            --template-file infra/main.bicep \
            --parameters @infra/params.single.json \
            --output table

    # Deploy (creates RG + Storage)
    - task: AzureCLI@2
      displayName: 'Deploy Storage + RG'
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "🚀 Deploying Storage + Resource Group..."
          az deployment sub create \
            --name "deploy-storage-$(Build.BuildId)" \
            --location "$(location)" \
            --template-file infra/main.bicep \
            --parameters @infra/params.single.json \
            --output table
          echo "✅ Deployment complete."
