jobs:
- job: CleanupFabricWorkspaces
  displayName: 'Cleanup specific Fabric workspaces from cleanup-workspaces.json'
  pool:
    name: 'Azure PreProd Pipelines'    # your self-hosted Windows pool

  variables:
  - name: environment
    value: 'dev'
  - name: dry_run          # 'true' = only log, 'false' = actually delete
    value: 'true'
  - group: fabric_$(environment)       # e.g. fabric_dev variable group

  steps:
  # 1. Install Fabric CLI
  - script: |
      "C:\Program Files\Python312\python.exe" -m pip install --upgrade pip
      "C:\Program Files\Python312\python.exe" -m pip install ms-fabric-cli
    displayName: 'Install Fabric CLI'

  # 2. Sanity check
  - script: |
      "C:\Program Files\Python312\Scripts\fab.exe" --version
    displayName: 'Fab Version'

  # 3. Authenticate Fabric CLI as service principal
  - script: |
      "C:\Program Files\Python312\Scripts\fab.exe" auth login -u $(dev_client_id) -p $(dev_client_secret) --tenant $(tenant_id)
    displayName: 'Fabric CLI Authentication'

  # 4. Delete only workspaces listed in cleanup-workspaces.json
  - task: PowerShell@2
    displayName: 'Delete Fabric workspaces listed in cleanup-workspaces.json'
    inputs:
      targetType: 'inline'
      script: |
        $ErrorActionPreference = 'Stop'

        $fabPath    = "C:\Program Files\Python312\Scripts\fab.exe"
        $configPath = "$(Build.SourcesDirectory)\infra\cleanup-workspaces.json"
        $dryRun     = "$(dry_run)" -eq "true"

        Write-Host "Using cleanup file: $configPath"
        Write-Host "DRY RUN mode: $dryRun"

        if (-not (Test-Path $configPath)) {
          throw "Cleanup config file not found: $configPath"
        }

        # 1) Get existing workspaces from Fabric
        Write-Host "Fetching existing workspaces using 'fab ls'..."
        $lsOutput = & $fabPath ls 2>&1

        Write-Host "DEBUG: raw 'fab ls' output:"
        $lsOutput | ForEach-Object { Write-Host "  $_" }

        # Extract workspace names from lines ending in '.Workspace'
        $existingNames = $lsOutput |
          Where-Object { $_ -match '\.Workspace\s*$' } |
          ForEach-Object {
            ($_ -split '\.Workspace')[0].Trim()
          }

        Write-Host "DEBUG: existing workspace names: $($existingNames -join ', ')"

        # 2) Load cleanup list (only these will be considered)
        $json     = Get-Content $configPath -Raw
        $cleanup  = $json | ConvertFrom-Json
        $cleanup  = @($cleanup)   # force array even if only one entry

        Write-Host "DEBUG: cleanup entries count = $($cleanup.Count)"

        if ($cleanup.Count -eq 0) {
          Write-Host "No entries in cleanup-workspaces.json – nothing to do."
          return
        }

        foreach ($item in $cleanup) {
          $name = [string]$item.workspaceName

          if ([string]::IsNullOrWhiteSpace($name)) {
            Write-Warning "Skipping entry with empty workspaceName in cleanup file."
            continue
          }

          Write-Host "---------------------------------------------"
          Write-Host "Requested delete for workspace: '$name'"

          if ($existingNames -notcontains $name) {
            Write-Host "  - Workspace '$name' not found in Fabric (according to 'fab ls') – skipping."
            continue
          }

          if ($dryRun) {
            Write-Host "  - DRY RUN: would delete workspace '$name' with: fab rm '$name.Workspace' --force"
            continue
          }

          Write-Host "  - Deleting workspace '$name'..."
          & $fabPath rm "$name.Workspace" --force
          $code = $LASTEXITCODE

          if ($code -eq 0) {
            Write-Host "  - Successfully deleted workspace '$name'."
          }
          else {
            Write-Warning "  - Failed to delete workspace '$name'. Exit code: $code"
          }
        }

        Write-Host "Cleanup pipeline finished processing all entries from cleanup-workspaces.json."
