jobs:
- job: DeployFabricWorkspaces
  displayName: 'Deploy Fabric workspaces from config'
  pool:
    name: 'Azure PreProd Pipelines'    # your self-hosted Windows pool

  variables:
  - name: environment
    value: 'dev'
  - group: fabric_$(environment)       # e.g. fabric_dev variable group

  steps:
  # 1. Install Fabric CLI
  - script: |
      "C:\Program Files\Python312\python.exe" -m pip install --upgrade pip
      "C:\Program Files\Python312\python.exe" -m pip install ms-fabric-cli
    displayName: 'Install Fabric CLI'

  # 2. Sanity check
  - script: |
      "C:\Program Files\Python312\Scripts\fab.exe" --version
    displayName: 'Fab Version'

  # 3. Authenticate Fabric CLI as service principal
  - script: |
      "C:\Program Files\Python312\Scripts\fab.exe" auth login -u $(dev_client_id) -p $(dev_client_secret) --tenant $(tenant_id)
    displayName: 'Fabric CLI Authentication'

  # 4. Create workspaces from JSON, using `fab ls` to decide what exists
  - task: PowerShell@2
    displayName: 'Create Fabric workspaces for all sources from config'
    inputs:
      targetType: 'inline'
      script: |
        $ErrorActionPreference = 'Stop'

        $fabPath    = "C:\Program Files\Python312\Scripts\fab.exe"
        # 👇 adjust if your file is somewhere else
        $configPath = "$(Build.SourcesDirectory)\infra\workspaces.json"

        Write-Host "Using config file: $configPath"

        if (-not (Test-Path $configPath)) {
          throw "Config file not found: $configPath"
        }

        # 1) Get current workspaces from Fabric with 'fab ls'
        Write-Host "Fetching existing workspaces using 'fab ls'..."
        $lsOutput = & $fabPath ls 2>&1

        Write-Host "DEBUG: raw 'fab ls' output:"
        $lsOutput | ForEach-Object { Write-Host "  $_" }

        # Lines ending in '.Workspace' correspond to workspace items.
        # Extract the string before '.Workspace' as the workspace name.
        $existingNames = $lsOutput |
          Where-Object { $_ -match '\.Workspace\s*$' } |
          ForEach-Object {
            ($_ -split '\.Workspace')[0].Trim()
          }

        Write-Host "DEBUG: existing workspace names: $($existingNames -join ', ')"
        function New-FabItem {
                  param(
                    [Parameter(Mandatory = $true)][string]$Path,  # e.g. ws-mdf-dev02.Workspace/Lakehouses/bronze
                    [Parameter(Mandatory = $true)][string]$Type   # 'Folder' or 'Lakehouse'
                  )
        
                  Write-Host "    - Creating $Type '$Path.$Type'..."
                  & $fabPath create "$Path.$Type"
                  $code = $LASTEXITCODE
        
                  if ($code -ne 0) {
                    throw "Failed to create $Type '$Path' (exit code $code)."
                  }
                }
        # 2) Load JSON config (array of objects)
        $json       = Get-Content $configPath -Raw
        $workspaces = $json | ConvertFrom-Json
        $workspaces = @($workspaces)   # force array even if only one entry

        Write-Host "DEBUG: workspaces.Count = $($workspaces.Count)"

        # 3) Loop each workspace from config
        for ($i = 0; $i -lt $workspaces.Count; $i++) {
          $ws = $workspaces[$i]

          $name     = [string]$ws.workspaceName
          $source   = [string]$ws.source
          $capacity = [string]$ws.capacityName
          $admin    = [string]$ws.adminObjectId

          if ([string]::IsNullOrWhiteSpace($name)) {
            Write-Warning "Skipping index $i: no workspaceName"
            continue
          }
          if ([string]::IsNullOrWhiteSpace($capacity)) {
            throw "capacityName is missing at index $i for workspaceName '$name'"
          }
          if ([string]::IsNullOrWhiteSpace($admin)) {
            throw "adminObjectId is missing at index $i for workspaceName '$name'"
          }

          Write-Host "---------------------------------------------"
          Write-Host "Index       : $i"
          Write-Host "source      : $source"
          Write-Host "name        : '$name'"
          Write-Host "capacity    : $capacity"
          Write-Host "adminObject : $admin"

          # 4) Decide based on `fab ls` result, NOT exit codes
          if ($existingNames -contains $name) {
            Write-Host "  - 'fab ls' says workspace '$name' already exists – skipping create and ACL."
            continue
          }

          Write-Host "  - Workspace '$name' NOT found in 'fab ls' – creating..."
          & $fabPath create "$name.Workspace" -P "capacityname=$capacity"

          if ($LASTEXITCODE -ne 0) {
            throw "Failed to create workspace '$name'. Exit code: $LASTEXITCODE"
          }

          Write-Host "  - Setting admin ACL for new workspace..."
          & $fabPath acl set "$name.Workspace" -I $admin -R admin -f

          if ($LASTEXITCODE -ne 0) {
            throw "Failed to set admin ACL for workspace '$name'. Exit code: $LASTEXITCODE"
          }
          # 3) Create folder + lakehouse structure
          Write-Host "  - Creating default folder & lakehouse structure in workspace '$name'..."

          # Top-level folders
          New-FabItem -Path "$name.Workspace/Pipelines"   -Type "Folder"
          New-FabItem -Path "$name.Workspace/Notebooks"   -Type "Folder"
          New-FabItem -Path "$name.Workspace/Scripts"     -Type "Folder"
          New-FabItem -Path "$name.Workspace/Lakehouses"  -Type "Folder"

          # Lakehouses under Lakehouses folder (Bronze / Silver / Gold)
          New-FabItem -Path "$name.Workspace/Lakehouses/bronze" -Type "Lakehouse"
          New-FabItem -Path "$name.Workspace/Lakehouses/silver" -Type "Lakehouse"
          New-FabItem -Path "$name.Workspace/Lakehouses/gold"   -Type "Lakehouse"
        }

        Write-Host "All workspaces from config created with folder structure."
        }

        Write-Host "All workspaces from config processed."





        The below used for checking admn object for existing ones :
- task: PowerShell@2
  displayName: 'Create/Ensure Fabric workspaces + RBAC (Python when exists)'
  inputs:
    targetType: 'inline'
    script: |
      $ErrorActionPreference = 'Stop'

      $fabPath     = "C:\Program Files\Python312\Scripts\fab.exe"
      $py          = "C:\Program Files\Python312\python.exe"
      $configPath  = "$(Build.SourcesDirectory)\infra\workspaces.json"

      if (-not (Test-Path $configPath)) { throw "Config file not found: $configPath" }

      # Install Py deps (for ensure_rbac.py) once
      & $py -m pip install -U pip requests azure-identity

      # list existing workspaces by name
      Write-Host "Fetching existing workspaces using 'fab ls'..."
      $lsOutput = & $fabPath ls 2>&1
      $existingNames = $lsOutput |
        Where-Object { $_ -match '\.Workspace\s*$' } |
        ForEach-Object { ($_ -split '\.Workspace')[0].Trim() }

      # helper: set multiple admins with fab.exe (for new workspaces path)
      function Ensure-Admins-Fab {
        param([string]$WorkspaceName, [string[]]$Admins)
        if (-not $Admins -or $Admins.Count -eq 0) { return }
        $Admins = $Admins | ForEach-Object { $_.ToString().Trim() } | Where-Object { $_ } | Select-Object -Unique
        foreach ($a in $Admins) {
          Write-Host "    - fab: ensuring Admin '$a' on '$WorkspaceName'..."
          & $fabPath acl set "$WorkspaceName.Workspace" -I $a -R admin -f
          if ($LASTEXITCODE -ne 0) { Write-Warning "      fab acl set failed for '$a' (exit $LASTEXITCODE) — continuing" }
        }
      }

      # load config rows
      $rows = Get-Content $configPath -Raw | ConvertFrom-Json
      $rows = @($rows)

      for ($i = 0; $i -lt $rows.Count; $i++) {
        $ws = $rows[$i]
        $name     = [string]$ws.workspaceName
        $capacity = [string]$ws.capacityName

        # admins can be adminObjectIds[] (preferred) or legacy adminObjectId
        $admins = @()
        if ($ws.PSObject.Properties.Name -contains 'adminObjectIds') {
          $admins = @($ws.adminObjectIds)
        } elseif ($ws.PSObject.Properties.Name -contains 'adminObjectId' -and $ws.adminObjectId) {
          $admins = @("$($ws.adminObjectId)")
        }

        if ([string]::IsNullOrWhiteSpace($name))     { Write-Warning "Skip index $i: no workspaceName"; continue }
        if ([string]::IsNullOrWhiteSpace($capacity)) { throw "capacityName missing at index $i for '$name'" }

        Write-Host "-------------------------------------------------"
        Write-Host "[$i] Workspace : $name"
        Write-Host "     Capacity  : $capacity"
        Write-Host "     Admins    : $($admins -join ', ')"

        if ($existingNames -contains $name) {
          Write-Host "  - Workspace exists → calling Python ensure_rbac.py (adds any missing Admins)…"
          # Use SPN creds for Python, if you’re not running under AzureCLI@2:
          $env:TENANT_ID     = "$(tenant_id)"
          $env:CLIENT_ID     = "$(dev_client_id)"
          $env:CLIENT_SECRET = "$(dev_client_secret)"
          $env:WORKSPACE_RBAC_FILE = $configPath
          $env:WORKSPACE_FILTER    = $name
          & $py -u .\.deploy\ensure_rbac.py
          if ($LASTEXITCODE -ne 0) { throw "ensure_rbac.py failed (exit $LASTEXITCODE)" }
          continue
        }

        # Create and then set admins (using fab.exe path)
        Write-Host "  - Creating workspace '$name' on capacity '$capacity'..."
        & $fabPath create "$name.Workspace" -P "capacityname=$capacity"
        if ($LASTEXITCODE -ne 0) { throw "Failed to create workspace '$name' (exit $LASTEXITCODE)" }

        Write-Host "  - Setting Admins on new workspace (fab)..."
        Ensure-Admins-Fab -WorkspaceName $name -Admins $admins

        # optional: default folders & lakehouses
        function New-FabItem { param([string]$Path,[string]$Type)
          Write-Host "    - Creating $Type '$Path.$Type'..."
          & $fabPath create "$Path.$Type"
          if ($LASTEXITCODE -ne 0) { throw "Failed to create $Type '$Path' (exit $LASTEXITCODE)." }
        }
        New-FabItem -Path "$name.Workspace/Pipelines"  -Type "Folder"
        New-FabItem -Path "$name.Workspace/Notebooks"  -Type "Folder"
        New-FabItem -Path "$name.Workspace/Scripts"    -Type "Folder"
        New-FabItem -Path "$name.Workspace/Lakehouses" -Type "Folder"
        New-FabItem -Path "$name.Workspace/Lakehouses/bronze" -Type "Lakehouse"
        New-FabItem -Path "$name.Workspace/Lakehouses/silver" -Type "Lakehouse"
        New-FabItem -Path "$name.Workspace/Lakehouses/gold"   -Type "Lakehouse"
      }

      Write-Host "All workspaces processed (created if missing; RBAC ensured)."


