trigger: none

variables:
  - group: fabric_common

stages:
- stage: DeployDev
  displayName: 'Deploy Fabric Workspaces to Dev'
  variables:
    - name: environment
      value: 'dev'
    - group: fabric_${{ variables.environment }}
  jobs:
  - job: DeployWorkspaces
    displayName: 'Deploy Two Workspaces'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        python -m pip install --upgrade pip
        pip install ms-fabric-cli
      displayName: 'Install Fabric CLI'

    - script: |
        fab auth login -u $(azure_client_id) -p $(azure_client_secret) --tenant $(azure_tenant_id)
      displayName: 'Fabric CLI Authentication'
    
    - script: |
        fab create $(workspace_name_mdf).Workspace -P capacityname=$(fabric_capacity_name)
        fab acl set $(workspace_name_mdf).Workspace -I $(workspace_admin_id) -R admin -f
      displayName: 'Create & Set Admin for MDF Workspace'

    - script: |
        fab create $(workspace_name_dataengineering).Workspace -P capacityname=$(fabric_capacity_name)
        fab acl set $(workspace_name_dataengineering).Workspace -I $(workspace_admin_id) -R admin -f
      displayName: 'Create & Set Admin for Data Engineering Workspace'

- stage: DeployTest
  displayName: 'Deploy Fabric Workspaces to Test'
  variables:
    - name: environment
      value: 'test'
    - group: fabric_${{ variables.environment }}
  jobs:
  - job: DeployWorkspaces
    displayName: 'Deploy Two Workspaces'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        python -m pip install --upgrade pip
        pip install ms-fabric-cli
      displayName: 'Install Fabric CLI'

    - script: |
        fab auth login -u $(azure_client_id) -p $(azure_client_secret) --tenant $(azure_tenant_id)
      displayName: 'Fabric CLI Authentication'
    
    - script: |
        fab create $(workspace_name_mdf).Workspace -P capacityname=$(fabric_capacity_name)
        fab acl set $(workspace_name_mdf).Workspace -I $(workspace_admin_id) -R admin -f
      displayName: 'Create & Set Admin for MDF Workspace'

    - script: |
        fab create $(workspace_name_dataengineering).Workspace -P capacityname=$(fabric_capacity_name)
        fab acl set $(workspace_name_dataengineering).Workspace -I $(workspace_admin_id) -R admin -f
      displayName: 'Create & Set Admin for Data Engineering Workspace'

# ...repeat for Prod, etc.
